title:   Ajit Manandhar
logo: "/images/Ajit Profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a Data Analyst based in Sudbury, responsible for data analytics and visualization tasks, experience in the marketing and retail industry.
  <br><br>
Certified Data Analyst with over a year of hands-on experience in statistical data analysis and research. Specializes in managing, 
interpreting, analyzing, and presenting data to support decision-making processes in all types and sizes of organizations.  Able to 
support organizations in predicting trends, and better understanding the needs of their customers by analyzing and interpreting results. 
Skilled with drafting concise reports, maintaining databases, and work independently. Curious to learn about business who is value-driven, 
proactive, and critical-minded. Passionate in Digital Marketing Analytics and A/B testing. Hold current Ontario driver’s licence and have
access to vehicle. 
<br><br>
  <a href="https://www.linkedin.com/in/ajitmanandhar/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/ajit.manandhar">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/ajitmanandhar/About-Me-Ajit-Manandhar-494e070cea714cfc95d32b30a3c8d998">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal
 
