title:   Ajit Manandhar
logo: "/images/Ajit Profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a Data Analyst based in Sudbury, responsible for data analytics and visualization tasks, experience in the software (gaming) industry.
  <br><br>
  Perceptive and logical professional with proven ability to communicate with both technical professionals and end users to identify and translate business requirements. Proven ability to work with talented professionals to develop valuable process solutions to meet business objectives. 
  <br><br>
  <a href="https://www.linkedin.com/in/ajitmanandhar/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/ajit.manandhar">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/ajitmanandhar/About-Me-Ajit-Manandhar-494e070cea714cfc95d32b30a3c8d998">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal
 
