title:   Ajit Manandhar
logo: "/images/Ajit Profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
<br><br>
  A process-driven, team-oriented and ambitious Data Analyst with over a year of hands-on experience in statistical data analysis and research. Passionate about 
  helping business succeed by managing, interpreting, analyzing, and presenting data to support decision-making processes.
  <br><br>
  Knowledgeable on Statistics and Data
  Analytics possessing strong technical skills. Capable of drafting concise ad hoc reports, predicting trends and interpreting results to translate business data
  into substantial deliverables.
  <br><br>
  <a href="https://www.linkedin.com/in/ajitmanandhar/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/ajit.manandhar">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/ajitmanandhar/About-Me-Ajit-Manandhar-494e070cea714cfc95d32b30a3c8d998">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal
 
